-- Name: Haris Mahmood
-- ID: 40135271

-- PART 1: DDL QUERIES FOR CREATING THE DATABASE
-- MySQL was utilized for the creation of this Local Database Assignment

CREATE DATABASE MOVIE;
USE MOVIE;

CREATE TABLE CONTENTRATING(
	contentRating_id INT AUTO_INCREMENT PRIMARY KEY,
	rating_name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE MOVIE (
    movie_id INT AUTO_INCREMENT PRIMARY KEY,
    imdb_id VARCHAR(20) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    plot TEXT,
    rating DECIMAL(3, 1),
    content_rating_id INT,
    runtime INT,
    num_reviews INT,
    release_year INT,
    akas TEXT,
    FOREIGN KEY (content_rating_id) REFERENCES CONTENTRATING(contentRating_id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE GENRES (
	genres_id INT AUTO_INCREMENT PRIMARY KEY,
	genre_name VARCHAR(255) NOT NULL,
	movie_id INT,
	FOREIGN KEY (movie_id) REFERENCES MOVIE(movie_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COUNTRY (
	country_id INT AUTO_INCREMENT PRIMARY KEY,
	country_name VARCHAR(255) NOT NULL,
	country_code CHAR(2) NOT NULL,
	movie_id INT,
	FOREIGN KEY (movie_id) REFERENCES MOVIE(movie_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MovieLanguage (
	language_id INT AUTO_INCREMENT PRIMARY KEY,
	language_name VARCHAR(255) NOT NULL,
	movie_id INT,
	FOREIGN KEY (movie_id) REFERENCES MOVIE(movie_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE KEYWORDS (
	keywords_id INT AUTO_INCREMENT PRIMARY KEY,
	keyword_name VARCHAR(255) NOT NULL,
	movie_id INT,
	FOREIGN KEY (movie_id) REFERENCES MOVIE(movie_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PERSON (
	person_id INT AUTO_INCREMENT PRIMARY KEY,
	imdb_id VARCHAR(20) UNIQUE NOT NULL,
	person_name VARCHAR(255) NOT NULL
);

CREATE TABLE ACTOR (
	actor_id INT AUTO_INCREMENT PRIMARY KEY,
	person_id INT,
	movie_id INT,
	character_name VARCHAR(255) NOT NULL,
	FOREIGN KEY (person_id) REFERENCES PERSON(person_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (movie_id) REFERENCES MOVIE(movie_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DIRECTOR (
	director_id INT AUTO_INCREMENT PRIMARY KEY,
	person_id INT,
	movie_id INT,
	FOREIGN KEY (person_id) REFERENCES PERSON(person_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (movie_id) REFERENCES MOVIE(movie_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CREATOR (
	creator_id INT AUTO_INCREMENT PRIMARY KEY,
	person_id INT,
	movie_id INT,
	FOREIGN KEY (person_id) REFERENCES PERSON(person_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (movie_id) REFERENCES MOVIE(movie_id) ON DELETE CASCADE ON UPDATE CASCADE
);
